---
title: "Home"
output:
  html_document:
    toc: true
---

This is a website for organizing my reading notes of research papers and a few books.

If you have any question about this project, please feel free to contact me:
[Qian Feng](https://qianfeng2.github.io), `fengq2@student.unimelb.edu.au`.

***

## Integrative Genomics

### [PECA model]()

- A survey of combinatorial methods for phylogenetic networks.* Huson and Scornavacca, Genome Biol. Evol., 2011.* 
- Paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3017387/pdf/evq077.pdf
- Note: http://web.stanford.edu/~zduren/PECA/

### [Omnigenic model]()

- Boyle, E. A., Li, Y. I., & Pritchard, J. K. (2017). An Expanded View of Complex Traits: From Polygenic to Omnigenic. *Cell*.
- Paper: https://www.ncbi.nlm.nih.gov/pubmed/28622505 

***

## Electronic Medical/Health Records

### [Analysis of insurance claims]()

- Wang, K., Gaitsch, H., Poon, H., Cox, N. J., & Rzhetsky, A. (2017). Classification of common human diseases derived from shared genetic and environmental determinants. *Nat. Genet.*
- Paper: http://www.nature.com/ng/journal/v49/n9/full/ng.3931.html

### [TreeWAS model]()

- Cortes, A., Dendrou, C., Motyer, A., Jostins, L., Vukcevic, D., Dilthey, A., Donnelly, P., Leslie, S., Fugger, L., & McVean, G. (2017). Bayesian analysis of genetic association across tree-structured routine healthcare data in the UK Biobank. *Nat. Genet.*
- Paper: https://www.nature.com/ng/journal/v49/n9/full/ng.3926.html 
- Software: https://github.com/mcveanlab/TreeWAS

### [Stochastic compartmental model for infection]()

- Cule, M. & Donnelly, P. (2017). Stochastic modelling and inference in electronic hospital databases for the spread of infections: Clostridium difficile transmission in Oxfordshire hospitals 2007–2010. *Ann. Appl. Stat.*
- Paper: https://projecteuclid.org/euclid.aoas/1500537718

***

## Han Chinese Population Genetics

### Major depressive disorder GWAS

- Converge Consortium. (2015). Sparse whole genome sequencing identifies two loci for major depressive disorder. *Nature.*
- Paper: http://www.nature.com/nature/journal/v523/n7562/full/nature14659.html

### Genetic variation

- Charleston W. K. Chiang, Serghei Mangul, Christopher R. Robles, Warren W. Kretzschmar, Na Cai, Kenneth S. Kendler, Sriram Sankararam, Jonathan Flint. (2017). A comprehensive map of genetic variation in the world's largest ethnic group - Han Chinese. *bioRxiv.*
- Preprint: https://www.biorxiv.org/content/early/2017/07/13/162982

***

## Statistical Genetics

### [An incomplete list of fine mapping methods](fine_mapping)
